version: '3.8'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: berionikkk/yamdb:latest
    restart: always
    volumes:
      - static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - static:/code/static
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
