# Generated by Django 3.0.5 on 2020-11-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201121_2156'),
        ('api', '0006_auto_20201121_2216'),
    ]

    operations = [
    ]
